### PR TITLE
Bootstrap 4.0.x - upgrade to Struts 6.3.0

### PR DESCRIPTION
**Pull request by gregh3269**
Updated 4.0.1 to work on struts 6.1.2.  Although I am not 100% sure as I refactored it by comparing with v5.  Roller won't work on the 6.3.x. without some changes, so can only test it on 6.1.2

### CODE REVIEW

**Comment by lukaszlenart** [comment]
There are some conflicts

**Comment by lukaszlenart** [comment]
@gregh3269 could you grant me access to your fork? I made changes locally but cannot pus them

**Comment by lukaszlenart** [comment]
@gregh3269 having Struts 6.3.0 is ok?

**Comment by gregh3269** [comment]
Yes latest version.  I will upgrade the app and make sure it works.  Thanks.

**Comment by gregh3269** [comment]
Think some of the jars need bumping, ie commons-io from 2.8.0 to 2.9.0.

**Comment by lukaszlenart** [comment]
> Think some of the jars need bumping, ie commons-io from 2.8.0 to 2.9.0.

Let's do it in separated PRs and I've enabled Renovate bot to take care of outdated dependencies.

**Comment by gregh3269** [comment]
To test with latest struts, I upgraded roller and all is good on the ui (easy upgrade, just a few org.apache.struts2.action.ParametersAware etc refactors). 
 
Cheers

**Comment by gregh3269** [comment]
Is there a rc/tag so I can test for real?

**Comment by lukaszlenart** [comment]
> Is there a rc/tag so I can test for real?

Nope, I will add propagation of -SNAPSHOT

**Comment by gregh3269** [comment]
Thanks, runs OK. 

..Just changed the jar to 4.0.2-SNAPSHOT, did not need to add the nexus repo.

Will look at the showcase, hopefully its just pom changes.

**Comment by gregh3269** [comment]
I have done a few changes to get it to work with the showase, sorry.  I have compared it and it's like for like with 4.0.1.

Not sure what to do now as it seems to have added it on to the last commit?

Commits on Oct 7, 2023

    [Fixes to work correctly with showcase.]

**Comment by lukaszlenart** [comment]
That should solved the problem #141

**Comment by gregh3269** [comment]
Sorry, there is another one, showcase need to upgrade  struts2-jquery-plugin.  (This is also using struts2-velocity-plugin 6.1.2)

`https://github.com/struts-community-plugins/struts2-bootstrap/commit/7bec1f640db47f110a88ad6225f0d6b3bb95cc72`

**Comment by lukaszlenart** [comment]
But this is already done in the `release/4.0.x` branch

**Comment by lukaszlenart** [comment]
https://github.com/struts-community-plugins/struts2-bootstrap/blob/release/4.0.x/struts2-bootstrap-showcase/pom.xml#L17

**Comment by gregh3269** [comment]
OK, my local branch is stale.

From yesterday this should fix everything.

`https://github.com/struts-community-plugins/struts2-bootstrap/commit/24fb594bc1125c845833907229ccb533b2fb691c`

(sorry it has got a bit messy now).

**Comment by lukaszlenart** [comment]
Great, I cherry-picked your changes, please review #141

**Comment by gregh3269** [comment]
I will rebase and do another pr as there will be merge conflicts.

**Comment by gregh3269** [comment]
I rechecked all the templates

`https://github.com/struts-community-plugins/struts2-bootstrap/compare/release/4.0.x...gregh3269:struts2-bootstrap:release/4.0.x
`

Not too sure about, don't know the previous history of the changes eg j_string:

====

controlheader-core.ftl

Including

```
<#if (parameters.dynamicAttributes?? && parameters.dynamicAttributes?size > 0 && parameters.dynamicAttributes["formLabelCssClass"]??)><#rt/>
    <#assign formLabelCssClass = parameters.dynamicAttributes.remove("formLabelCssClass")/><#rt/>
<#else>
    <@s.if test="#s2b_form_class == 'form-horizontal'">
        <#assign formLabelCssClass >col-form-label</#assign><#rt/>
    </@s.if><#rt/>
    <@s.else>
        <#assign formLabelCssClass >form-label</#assign><#rt/>
    </@s.else><#rt/>
</#if><#rt/>
```

 gives extra spacing on labels. ie adds col-form-label class

```
<label class="col-form-label col-sm-3" for="index_password">Password    
  <i class="bi bi-info-circle s2b_tooltip" data-toggle="tooltip" title="Enter your Password here"></i>
</label>
```

Is this a bug or something for v5?

====

inputtransferselect.ftl

v4 branch > tested working

<@s.script type="text/javascript" src="${parameters.staticContentPath}/inputtransferselect.js"/>

v5 branch > extra ${base}

<@s.script src="${base}${parameters.staticContentPath}/inputtransferselect.js" encode='false' includeParams='none'/>

====

optiontransferselect.ftl

v4 branch > tested working

<@s.script type="text/javascript" src="${parameters.staticContentPath}/optiontransferselect.js"/>

v5 branch > extra ${base} 

<@s.script src="${base}${parameters.staticContentPath}/optiontransferselect.js" encode='false' includeParams='none'/>

====

submit.ftl

v5 branch > extra include

<#include "/${parameters.templateDir}/${parameters.expandTheme}/controlheader.ftl" />

====

submit-close.ftl

v5 branch > extra include

<#include "/${parameters.templateDir}/${parameters.expandTheme}/controlfooter.ftl" />

====

simple/select.ftl

v5 branch > there is an extra <#rt/> is this needed?

<option value="${parameters.headerKey}"<#rt/>

====

If these are correct I can do a pr.

**Comment by lukaszlenart** [comment]
Is it related to my PR #141 ? Maybe we can merge it and you can prepare your changes? And I can grant to direct access to this project so you don't have to use your fork anymore, wdyt?

**Comment by gregh3269** [comment]
It's more of a formatting thing, (breaking pixel perfection) and not really knowing freemarker as there are differences see notes above (eg v5 branch > extra ${base}).

I think this version its pretty much the same as your PR but includes some @s.script also, I will do the mb-3 fix, maybe get the guys to check it before merging.

**Comment by gregh3269** [comment]
...more testing. The console logs (x24 on the index.action):

2023-10-17 09:41:38,341 WARN  [ajp-nio-127.0.0.1-8009-exec-4] ognl.SecurityMemberAccess (SecurityMemberAccess.java:112) - Access to non-public [protected java.lang.String org.apache.struts2.components.UIBean.disabled] is blocked!

Only UIBean.disabled.

Tracing one, it comes from from the radio tag (same also on v5). 

```
<s:radio
                        tooltip="Choose your Best Friend"
                        label="Best Friend"
                        formGroupCssClass="row"
                        list="{'Wes', 'Patrick', 'Jason', 'Jay', 'Toby', 'Rene'}"
                        name="bestFriend"
                        cssErrorClass="foo"/>
```
Bit of a vague message, does not give any hints on what to do.

**Comment by lukaszlenart** [comment]
`${base}` is needed as it represents servlet context `/my-app` about the rest I'm not sure. We can fix them one by one. Also fixed the security warning about `disabled`, all in my PR #141

**Comment by gregh3269** [comment]
Yes after much retesting ({base}) was needed.  Is it possible to merge these 6 commits? Should be OK, there were some more missings/bugs/dtd changes.  My branch says:  This branch is [6 commits ahead] [3 commits behind] struts-community-plugins:release/4.0.x.  The 3 behind are unrelated?

**Comment by gregh3269** [comment]
..Looking at version 5 the side bar is missing 

```
SEVERE: Servlet.service() for servlet [jsp] threw exception
org.apache.jasper.JasperException: The absolute uri: [http://java.sun.com/jsp/jstl/core] cannot be resolved in either web.xml or the jar files deployed with this application
```

and is using/missing jstl.

includes/menu.jsp
```
<%@ taglib uri="http://java.sun.com/jsp/jstl/core" prefix="c" %>
<c:set var="activeMenu" value="${param.active}" scope="page"/>
```
showcase pom needs
```
<dependencies>
    ........
    <dependency>
        <groupId>javax.servlet</groupId>
	    <artifactId>jstl</artifactId>
	    <version>1.2</version>
    </dependency>
</dependencies>
```

**Comment by lukaszlenart** [comment]
The PR got merged and I invited you to the org hooding the plugins - please remove your fork and clone the origin. And could you create issues in proper projects? Resolving all the issues in this PR won't be helpful for others in the future.

**Comment by gregh3269** [comment]
I retested the 4.0.x and it does not work correctly, has commits missing from my previous mess.  (I typically run a rolling release so don't have much experience with git here).  I reset my fork and created 4.0.2-struts-6.3.0.1 (which works), but I think other changes have occurred upstream.  Not sure how to get these back into sync with my working 4.0.2-struts-6.3.0.  Rebase on this and then apply the upstream changes?

**Comment by lukaszlenart** [comment]
I rebased the release/4.0.x branch over your branch #148 - I can merge it and you can check again

**Comment by gregh3269** [comment]
I have copied the missing commits into my local branch of feature/rebase-4.x, the rebase seems not correct.  I have left other commits unchanged.  I have tested it and looks correct with no warnings other than:

2023-10-24 11:32:05,286 WARN  [ajp-nio-127.0.0.1-8009-exec-2] components.ServletUrlRenderer (ServletUrlRenderer.java:213) - No configuration found for the specified action: 'vertical' in namespace: '/'. Form action defaulting to 'action' attribute's literal value.

Not sure how to fix this one.

OK to push to feature/rebase-4.x branch?

**Comment by lukaszlenart** [comment]
Sure, push your changes

**Comment by gregh3269** [comment]
I have checked v5 and there are some minor fixes, ok to push to v5 or would I need to do a ticket?

**Comment by lukaszlenart** [comment]
Please open a PR against the branch - it fits better when preparing a new release, users can notices what has changed like here [5.0.2](https://github.com/struts-community-plugins/struts2-bootstrap/releases/tag/5.0.2)

**Comment by gregh3269** [comment]
(Remember I have not done this before on gh).  It has passed the checks, just do the merge pull request button?

**Comment by lukaszlenart** [comment]
> (Remember I have not done this before on gh). It has passed the checks, just do the merge pull request button?

I left one comment, but looks good. Once I approve the PR you can hit the merge button :)

**Comment by gregh3269** [comment]
.....Just a thought

The app used jstl (which was not needed) to access the active parameter in the included page.

```
<s:include value="includes/topMenu.jsp">
    <s:param name="active">home</s:param>
</s:include>
```
The page https://struts.apache.org/tag-developers/include-tag gives some hints on the using the parameter ${param.ParamName}.  It might be worth adding a bit more info about accessing the variable in the included page eg

`<s:set var="myParam" scope="page">${param.ParamName}}</s:set>`

Possibly may not have used jstl if this was made obvious in the docs.

**Comment by lukaszlenart** [comment]
Great, something like [this](https://github.com/apache/struts-site/pull/210) is ok? Also I'm going removes JSTL as a dependency

**Pull request merged**
