### PR TITLE
fix showcase application for bootstrap 4

### PR DESCRIPTION
**Pull request by sdutry**
# Work in Progress

### Related Issues
-  #36 
-  #29 

### reason for early pull request
to get reviews with ideas for alternatives / better solutions.

### dynamic attributes not available
@lukaszlenart 
any ideas on how to fix the elements without dynamic attributes:
- `doubleselect`
- `optiontransferselect`
- `inputtransferselect`

### CODE REVIEW

**Comment by lukaszlenart** [comment]
@sdutry what do you mean by _elements without dynamic attributes_? All UI tags have _dynamic attributes_ and these three tags are based on `select` tag so DA should just work.

**Review by jogep — APPROVED** [review]

**Comment by jogep** [comment]
@lukaszlenart I can confirm that it is not working for this three tags as mentioned by @sdutry. However I found a workaround but would be better if we can adjust this in STruts itself to support DA in future here as well. 

Resolving this issue as new version is now working based on bootstrap 4.6.0

**Comment by lukaszlenart** [comment]
Hm.. ok, I will double check and address that in Struts itself.

**Comment by lukaszlenart** [comment]
I will try to fix them https://issues.apache.org/jira/browse/WW-5129, thanks!

**Comment by lukaszlenart** [comment]
As far I see, the problem is that the first `<select/`> is based on `select` tag from `simple` theme, where the second `<select/>` is created manually without a reference to `dynamic-attributes.ftl` - I assume it would be good to have a second set of DA related to the second `<select/>`

**Pull request merged**
